package com.example.kotlin_covid19_app.common

const val ACCOUNT_NAME_KEY = "ACCOUNT_NAME_KEY"
const val ACCOUNT_DESCRIPTION_KEY = "ACCOUNT_CLUB_KEY"
const val ACCOUNT_AVATAR_KEY = "ACCOUNT_AVATAR_KEY"
const val MOVIE_OBJECT_KEY = "MOVIE_OBJECT_KEY"
const val DATABASE_NAME = "MOVIES_DATABASE.db"
const val PREFERENCE_NAME = "SETTING_FILES"
const val CODE_ADD_NEW_ACCOUNT = 12
const val CODE_ADD_UPDATE_ACCOUNT = 13